remote_theme: mmistakes/minimal-mistakes

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
